// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clientstream.proto

package com.example.calculator;

public interface ComputeAverageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sample.ComputeAverageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double average = 1;</code>
   */
  double getAverage();
}
