// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clientstream.proto

package com.example.calculator;

public interface ComputeAverageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sample.ComputeAverageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   */
  int getNumber();
}
