// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: unary.proto

package com.example.grpc;

public interface SumRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SumRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 first_number = 1;</code>
   */
  int getFirstNumber();

  /**
   * <code>int32 second_number = 2;</code>
   */
  int getSecondNumber();
}
