// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: unary.proto

package com.example.grpc;

public interface SumResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SumResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 sum_result = 1;</code>
   */
  int getSumResult();
}
