// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serverstream.proto

package com.example.grpc;

public interface PrimeNumberDecompositionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PrimeNumberDecompositionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 prime_factor = 1;</code>
   */
  int getPrimeFactor();
}
