// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serverstream.proto

package com.example.grpc;

public interface PrimeNumberDecompositionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PrimeNumberDecompositionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   */
  int getNumber();
}
